---
# This role will install MySQL and create db user and give permissions.
- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
- name: Install MySQL
  apt: package={{ item }} state=present update_cache=yes

  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ MySQL_root_pass }}" login_user=root
- name: Secures the MySQL root user
  mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{MySQL_root_pass}}" login_user=root
  with_items:
    - 172.17.0.4
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"
- name: Removes the MySQL test database
  mysql_db: db=dbtest state=absent login_password="{{ MySQL_root_pass }}" login_user=root
- name: Create the MySQL dbtest database
  mysql_db: db=dbtest state=present login_password="{{ MySQL_root_pass }}" login_user=root
